# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('image_file', models.ImageField(upload_to=models.CharField(max_length=64))),
            ],
        ),
    ]
