# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='key',
            field=models.BinaryField(),
        ),
    ]
