# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:10
from __future__ import unicode_literals

import captcha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=captcha.models.set_tag_folder),
        ),
    ]
